#ifndef CONSOLE_H
#define CONSOLE_H

#define COLOR_BASE_ADDR 0xB8000
#define MONO_BASE_ADDR 0xB0000

#define BASE_ADDRESS COLOR_BASE_ADDR
#define ATTRIBUTE_BYTE ((__u8)0x07)
#define TAB_WIDTH 8

#endif // CONSOLE_H

