#ifndef KERNEL_ARCH_X86_64_ADDRESSES_H
#define KERNEL_ARCH_X86_64_ADDRESSES_H

#define KERNEL_PHYSICAL_BASE 0x100000 // 1 MB
#define KERNEL_VIRTUAL_OFFSET 0xFFFFFFFF80000000
#define KERNEL_VIRTUAL_BASE (KERNEL_VIRTUAL_OFFSET + KERNEL_PHYSICAL_BASE)

#endif /* KERNEL_ARCH_X86_64_ADDRESSES_H */

